// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDenmQohjinVOgBwVQMK5BRg0aXJLTmfVQ',
    appId: '1:763902133969:web:cb861f1c55454bfbcee7f0',
    messagingSenderId: '763902133969',
    projectId: 'dhego-fb024',
    authDomain: 'dhego-fb024.firebaseapp.com',
    storageBucket: 'dhego-fb024.firebasestorage.app',
    measurementId: 'G-R4GB1RS0P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5GO04c9rIZvNzK4VsBuKuDF3T1-9ZGHk',
    appId: '1:763902133969:android:f33f120f5e7f7c53cee7f0',
    messagingSenderId: '763902133969',
    projectId: 'dhego-fb024',
    storageBucket: 'dhego-fb024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXJ_mz9INLuyFgzgw1wRyZ_c6fkDo_GHw',
    appId: '1:763902133969:ios:2f1cc65568471a2ecee7f0',
    messagingSenderId: '763902133969',
    projectId: 'dhego-fb024',
    storageBucket: 'dhego-fb024.firebasestorage.app',
    iosBundleId: 'com.example.dhego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXJ_mz9INLuyFgzgw1wRyZ_c6fkDo_GHw',
    appId: '1:763902133969:ios:2f1cc65568471a2ecee7f0',
    messagingSenderId: '763902133969',
    projectId: 'dhego-fb024',
    storageBucket: 'dhego-fb024.firebasestorage.app',
    iosBundleId: 'com.example.dhego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDenmQohjinVOgBwVQMK5BRg0aXJLTmfVQ',
    appId: '1:763902133969:web:0b82a09034d0c419cee7f0',
    messagingSenderId: '763902133969',
    projectId: 'dhego-fb024',
    authDomain: 'dhego-fb024.firebaseapp.com',
    storageBucket: 'dhego-fb024.firebasestorage.app',
    measurementId: 'G-196C7LNSS0',
  );
}
